channels:
- conda-forge
- default
dependencies:
- boa
- conda-build
- python==3.10
- numpy>=1.17.0,<2
- pygmo=2.19.6
- pip
- pandas
- openpyxl
- matplotlib
- seaborn
- grpclib
- pytensor
- fmpy
- scikit-learn==1.4.2
- scikit-optimize
- pip:
  - OMpython
  - pytensor-federated
  # - m2w64-toolchain only on windows
  # code testing
  - pytest
  - pytest-cov
  # doc building
  - sphinx
  - sphinx_rtd_theme
  - myst-parser
  - numpydoc
  - nbsphinx
  - nbsphinx_link
  - sphinx_copybutton
