channels:
- conda-forge
dependencies:
  - python>=3.10,<=3.13
  - numpy
  - pygmo>=2.19.6
  - pip
  - pip:
    - pandas<3
    - openpyxl
    - matplotlib
    - seaborn
    - grpclib
    - pytensor
    - fmpy
    - scikit-learn
    - scikit-optimize
    - pytensor-federated
    # for code testing
    - pytest
    - pytest-cov
  # - m2w64-toolchain  # [win]
  # for building
    - twine
    - wheel
  # sphinx extensions
    - -r docs/requirements.txt
