name: pipeline

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: '3.10'
        activate-environment: testim8
        environment-file: environment.yml
        auto-activate-base: false

    - name: setup OpenModelica compiler
      uses: OpenModelica/setup-openmodelica@v1.0
      with:
        version: 'stable'
        packages: |
          omc
        libraries: |
          'Modelica 4.0.0'

    - name: compile FMU
      shell: bash -l {0}
      run: |
        python tests/test_data/model_compilation.py --modelname Growth

    - name: Run tests
      shell: bash -l {0}
      run: |
        conda install libxcrypt
        export  CPATH=/usr/share/miniconda/envs/testim8/include/
        pip install -e .
        pytest -v --cov=estim8 --cov-report xml --cov-report term-missing estim8 tests/

    - name: Upload coverage
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        file: ./coverage.xml

    - name: Test Wheel build, install and import
      shell: bash -l {0}
      run: |
        python setup.py bdist_wheel
        twine check dist/*
        cd dist
        pip install estim8*.whl
        python -c "import estim8; print(estim8.__version__)"
